version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./etc/mongod.conf:/etc/mongod.conf
            - ./mongodb/data/db/:/data/db/
            - ./mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            WAIT_HOSTS: mongodb:27017
        ports:
            - "27017:27017"
        logging:
            options:
                max-size: 1g        
        command: ["-f", "/etc/mongod.conf"]
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: 500M

    webserver:
        image: raychorn/ubuntu_python38:latest
        container_name: dev1
        restart: unless-stopped
        ports:
            - "9000:9000"
        depends_on:
            - mongodb
        env_file:
            - .env
        entrypoint:
            - bash
        tty: true
        stdin_open: true
        networks:
            - frontend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
