version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./etc/mongod.conf:/etc/mongod.conf
            - ./mongodb/data/db/:/data/db/
            - ./mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            WAIT_HOSTS: mongodb:27017
        ports:
            - "27017:27017"
        logging:
            options:
                max-size: 1g        
        command: ["-f", "/etc/mongod.conf"]
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: 500M

    webserver:
        build: .
        container_name: dev1
        restart: unless-stopped
        volumes:
            - C:\Users\Owner\OneDrive\##projects\docker-projects\docker-mongo-dev1:/workspaces/docker-mongo-dev1
        ports:
            - "9000:9000"
        depends_on:
            - mongodb
        env_file:
            - .env
        entrypoint:
            - bash
        tty: true
        stdin_open: true
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1